before_script:
  - ansible-lint --version

stages:
  - ansible-lint

ansible-lint:
  stage: ansible-lint
  script:
    - ansible-lint roles/common/tasks/*.yml
    - ansible-lint deployServerOnAWS.yml
