---
# tasks file for docker

- name: Check if OS is support
  stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}"
  register: os_support

- name: Fail because OS "{{ ansible_distribution }}" isn't support by this role
  fail:
    msg: "Hello, your operating system is not support for now. Please refer to the documentation."
  when: not os_support.stat.exists

- name: Include vars from "{{ ansible_distribution }}".yml
  include_vars: "{{ ansible_distribution }}.yml"
  when:
    - action is defined
    - action in file_to_include

- name: Include tasks from "{{ ansible_distribution }}/{{ action }}".yml
  include_tasks: "{{ ansible_distribution }}/{{ action }}.yml"
  when:
    - action is defined
    - action in file_to_include

- name: Change Docker service status to "{{ state }}"
  service:
    name: docker
    state: "{{ state }}"
  when: state is defined

- name: Change enable status on boot at "{{ enable }}"
  service:
    name: docker
    enabled: "{{ enable | bool }}"
    state: started
  when: enable is defined