---
# tasks file for docker

- name: Check if OS is support
  stat:
    path: "{{ ansible_distribution | lower }}"
  register: os_support

- name: fail because OS isn't support by this role
  fail:
    msg: "Hello, your operating system is not support for now. Please refer to the documentation."
  when: not os_support

- name: Check if action exist
  stat:
    path: "{{ ansible_distribution | lower }}/{{ action }}.yml"
  register: action_exist

- name: Include tasks from "{{ ansible_distribution }}"
  include_tasks: "{{ ansible_distribution | lower }}/{{ action }}.yml"
  when:
    - ansible_distribution is defined
    - os_support.stat.isdir is defined
    - os_support.stat.isdir