---
# tasks file for docker on ubuntu servers

- name: Update APT cache && Upgrade APT to the latest packages
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install some packages
  apt:
    name: "{{ item }}"
    state: latest
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Deploy Docker's apt-key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present